version: "3"

services:
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/db-data:/var/lib/mysql
    networks:
      - internal
  #drush:
  #  image: drush/drush:8
  #  volumes:
  #    - ./volumes/drupal-data:/app
  drupal:
    image: "${PHP_IMAGE}:${PHP_VERSION}"
    container_name: drupal
    env_file: .env
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./volumes/drupal-data:/var/www

  webserver:
    image: "nginx:${NGINX_VERSION}"
    container_name: webserver
    env_file: .env
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/drupal-data:/var/www
      - ./nginx-conf:/etc/nginx/conf.d
      - ./volumes/certbot-etc:/etc/letsencrypt
    networks:
      - external

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./volumes/certbot-etc:/etc/letsencrypt
      - ./volumes/drupal-data:/var/www
    command: "certonly --webroot --webroot-path=/var/www/html --email ${LETS_ENCRYPT_EMAIL} --agree-tos --no-eff-email --staging -d ${NGINX_HOST}"

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

